---
all:
  children:
    cml_routers:
      hosts:
        R1:
          ansible_host: 192.168.255.101
        R2:
          ansible_host: 192.168.255.102
        R3:
          ansible_host: 192.168.255.103
        R4:
          ansible_host: 192.168.255.104
        R5:
          ansible_host: 192.168.255.105
      vars:
        ansible_network_os: cisco.ios.ios
        ansible_connection: network_cli
        ansible_user: cisco
        ansible_password: cisco
        ansible_become: true
        ansible_become_method: enable
        ansible_become_password: cisco