---
all:
  children:
    cml_routers:
      hosts:
        R1:
          ansible_host: 192.168.50.26
        R2:
          ansible_host: 192.168.50.194
        R3:
          ansible_host: 192.168.50.197
        R4:
          ansible_host: 192.168.50.64
        R5:
          ansible_host: 192.168.50.22
      vars:
        ansible_network_os: cisco.ios.ios
        ansible_connection: network_cli
        ansible_user: admin
        ansible_password: admin123
        ansible_become: true
        ansible_become_method: enable
        ansible_become_password: admin123